[package]
name = "axparameter_example"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
glib = { workspace = true }
log = { workspace = true }

acap-logging = { workspace = true, default-features = true }
axparameter = { workspace = true }
